### ISSUE TITLE
Initial UI Sketches

### ISSUE THREAD

**Issue by JordanRickman** [JordanRickman/story-web#3]
Produce sketches of the key UI design decisions.

_As a front-end developer, I need to know what key UI features I need to support, so that I can choose tech stack and design the software architecture._

**AC**
- Documents key UI elements.
- Clearly labels purpose of screen and of non-obvious elements.
- Lays out all important non-obvious screens. Obvious screens means things such as a login screen or settings screen that can be readily designed later simply by following common conventions.
- All sketches archived with sensible labeling and organization.

**Tasks**
- [ ] Determine where to archive sketches and other images.
- [ ] Archive initial sketch.
- [ ] Screen for viewing and filtering collections of elements, and typing up new ones. Card-style look/feel

**Comment by JordanRickman** [comment]
I would like a way to keep all out-of-band artifacts (sketches, standalone documents, etc) connected to the project. I would also like them in a centralized, organized place, where new versions can replace old ones - implying that attachments to GitHub issues wouldn't work well. I can test the support in GitHub's wiki, or link the project to a shared folder somewhere (Docs, Google Drive) and document that.
